baseURL = "https://stockholm-black-weekend.se"
languageCode = 'en-us'
theme = "shibui"
title = "BLACK WEEKEND"

[params.author]
name = "Stockholm Black Weekend"
email = "stockholm.black.weekend@gmail.com"

[menu]
  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 2
